table: customers
fields:
  - name: id
    type: integer
    nullable: true
  - name: name
    type: string
    nullable: true
  - name: email
    type: string
    nullable: true
  - name: status
    type: string
    nullable: true
  - name: country
    type: string
    nullable: true
  - name: created_date
    type: string
    nullable: true
  - name: updated_date
    type: string
    nullable: true
